services:
  matchmaking:
    image: andtechstudios/rematch
    ports:
      - 8080:8080
      - 7776:7776
      - 7777:7777
    restart: always
    volumes:
      - ./cert.json:/app/cert.json
      - ./cert.pfx:/app/cert.pfx
    environment:
      - SWT_CLIENT_USE_WSS=true
      - SWT_SSL_ENABLED=true
      #- CERT_PATH=cert.pfx
      #- CERT_PASSWORD=YOUR_CERT_PASSWORD_HERE
      #- CERT_CONTENT=YOUR_CERT_CONTENT_HERE
      #- CERT_CONTENT_IS_BASE64=false
    env_file:
      - .env